---
- name: Dump generated ACL for a given OS.
  hosts: localhost
  gather_facts: no
  
  tasks:
  - name: Run this module to generate an ACL
    capirca_acl:
      net_os: 'juniper'
    register: testout
  - name: Dump the resulting ACL
    debug:
      msg: '{{ testout.message }}'