---
name: CI

on: [push, pull_request]

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: ['3.6']
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/community/kubernetes

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible capirca ipaddress absl-py
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      # - name: Install ansible base (devel branch)
      #   run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check

      - name: Run integration tests on Python ${{ matrix.python_version }}
        run: ansible-test integration --docker -v --color --python ${{ matrix.python_version }}
        working-directory: ./ansible_collections/nleiva/capirca_acl