---
name: Ansible Galaxy

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get the version name from the tags
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Injecting a dynamic Collection version
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          galaxy_version: '${{ env.RELEASE_VERSION }}'